/**
 * Error Code System
 *
 * 格式: <模块>_<类别>_<具体错误>
 *
 * 模块:
 * - PLATFORM: 平台相关
 * - CATALOG: 目录相关
 * - SCANNER: 扫描相关
 * - INSTALLER: 安装相关
 * - TASK: 任务相关
 * - STORAGE: 存储相关
 */

export const ERROR_CODES = {
  // Platform Errors (1xxx)
  PLATFORM_UNSUPPORTED: 'PLATFORM_UNSUPPORTED',
  PLATFORM_DETECTION_FAILED: 'PLATFORM_DETECTION_FAILED',

  // Catalog Errors (2xxx)
  CATALOG_PARSE_ERROR: 'CATALOG_PARSE_ERROR',
  CATALOG_SCHEMA_INVALID: 'CATALOG_SCHEMA_INVALID',
  CATALOG_TOOL_NOT_FOUND: 'CATALOG_TOOL_NOT_FOUND',
  CATALOG_VERSION_NOT_FOUND: 'CATALOG_VERSION_NOT_FOUND',
  CATALOG_ASSET_NOT_MATCHED: 'CATALOG_ASSET_NOT_MATCHED',

  // Scanner Errors (3xxx)
  SCANNER_COMMAND_FAILED: 'SCANNER_COMMAND_FAILED',
  SCANNER_PATH_NOT_FOUND: 'SCANNER_PATH_NOT_FOUND',
  SCANNER_VERSION_PARSE_ERROR: 'SCANNER_VERSION_PARSE_ERROR',

  // Installer Errors (4xxx)
  INSTALLER_DOWNLOAD_FAILED: 'INSTALLER_DOWNLOAD_FAILED',
  INSTALLER_VERIFY_FAILED: 'INSTALLER_VERIFY_FAILED',
  INSTALLER_EXTRACT_FAILED: 'INSTALLER_EXTRACT_FAILED',
  INSTALLER_INSTALL_FAILED: 'INSTALLER_INSTALL_FAILED',
  INSTALLER_VALIDATE_FAILED: 'INSTALLER_VALIDATE_FAILED',

  // Task Errors (5xxx)
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_RUNNING: 'TASK_ALREADY_RUNNING',
  TASK_CANCELLED: 'TASK_CANCELLED',
  TASK_TIMEOUT: 'TASK_TIMEOUT',

  // Storage Errors (6xxx)
  STORAGE_READ_ERROR: 'STORAGE_READ_ERROR',
  STORAGE_WRITE_ERROR: 'STORAGE_WRITE_ERROR',
  STORAGE_MIGRATION_ERROR: 'STORAGE_MIGRATION_ERROR',

  // Unknown
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
    public details?: unknown
  ) {
    super(message);
    this.name = 'AppError';
  }
}
